export const FETCH_MESSAGES = 'FETCH_MESSAGES';

export const FETCH_MESSAGES_LOADING = 'FETCH_MESSAGES_LOADING';

export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';

export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const CREATE_MESSAGE_LOADING = 'CREATE_MESSAGE_LOADING';

export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';

export const CREATE_MESSAGE_FAILURE = 'CREATE_MESSAGE_FAILURE';

export const FETCH_MESSAGE = 'FETCH_MESSAGE';

export const FETCH_MESSAGE_LOADING = 'FETCH_MESSAGE_LOADING';

export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS';

export const FETCH_MESSAGE_FAILURE = 'FETCH_MESSAGE_FAILURE';
