export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_LOADING = 'FETCH_USERS_LOADING';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_LOADING = 'FETCH_USER_DATA_LOADING';
export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';
export const FETCH_USER = 'FETCH_USER';

export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_LOADING = 'GET_USER_INFO_LOADING';
export const GET_USER_INFO_ERROR = 'GET_USER_INFO_ERROR';
export const GET_USER_INFO = 'GET_USER_INFO';

export const EDIT_USER_INFO_SUCCESS = 'EDIT_USER_INFO_SUCCESS';
export const EDIT_USER_INFO_LOADING = 'EDIT_USER_INFO_LOADING';
export const EDIT_USER_INFO_ERROR = 'EDIT_USER_INFO_ERROR';
export const EDIT_USER_INFO = 'EDIT_USER_INFO';

export const SET_API_TOKEN_NOT_ASKED = 'SET_API_TOKEN_NOT_ASKED';
export const SET_API_TOKEN_SUCCESS = 'SET_API_TOKEN_SUCCESS';
export const SET_API_TOKEN_LOADING = 'SET_API_TOKEN_LOADING';
export const SET_API_TOKEN_FAILURE = 'SET_API_TOKEN_FAILURE';

export const SIGN_IN = 'SIGN_IN';

export const CLEAR_SESSION = 'CLEAR_SESSION';

export const FETCH_ROLES = 'FETCH_ROLES';
export const FETCH_ROLES_LOADING = 'FETCH_ROLES_LOADING';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_FAILURE = 'FETCH_ROLES_FAILURE';
